[features]
seeds = false
skip-lint = false
[programs.devnet]
helloworm = "GsTfE4Ndievuh8G5EWAPcS7aixwKyN5YdZNymq2cVfNV"

[programs.localnet]
helloworm = "GsTfE4Ndievuh8G5EWAPcS7aixwKyN5YdZNymq2cVfNV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
