import Head from "next/head";
import dynamic from "next/dynamic";
import { Divider, Row, Tabs } from "antd";

const BSCWallets = dynamic(() => import(`../components/BSCWallet`), {
  ssr: false,
});
const SOLWalletsProvider = dynamic(() => import(`../components/SOLWallet`), {
  ssr: false,
});
export default function Home() {
  return (
    <>
      <Head>
        <title>Hackathon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div
          style={{
            background: `linear-gradient(280deg,
      rgba(82,76,189,1) 0%, rgba(107,105,194,1) 2%, rgba(38,151,190,1) 100%)`,
            padding: 16,
            color: "white",
            minHeight: "100vh",
          }}
        >
          <Divider style={{ color: "white" }}>HACKATHON-2023 SOLANA</Divider>

          <Divider style={{ color: "white" }}>
            Choose your network you want to play
          </Divider>
          <Tabs
            items={[
              {
                key: "bsc",
                label: "BSC SmartChain",
                children: <BSCWallets />,
              },
              {
                key: "sol",
                label: "SOLANA Chain",
                children: <SOLWalletsProvider />,
              },
            ]}
          ></Tabs>
        </div>
      </main>
    </>
  );
}
