import Head from "next/head";
import { useWallet } from "@solana/wallet-adapter-react";
import dynamic from "next/dynamic";
import { Divider, Row } from "antd";

const Wallet = dynamic(() => import(`../components/Wallet`), { ssr: false });
export default function Home() {
  const { select, wallets, publicKey, disconnect } = useWallet();
  console.log(wallets);
  return (
    <>
      <Head>
        <title>Hackathon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div
          style={{
            background: `linear-gradient(280deg,
      rgba(82,76,189,1) 0%, rgba(107,105,194,1) 2%, rgba(38,151,190,1) 100%)`,
            padding: 16,
            color: "white",
            minHeight: "100vh",
          }}
        >
          <Divider style={{ color: "white" }}>HACKATHON-2023 SOLANA</Divider>
          <Wallet />
        </div>
      </main>
    </>
  );
}
